// web-client/src/routes/(auth)/login/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import Button from '$lib/components/ui/button.svelte';
	import InputContainer from '$lib/components/ui/input-container.svelte';
	import Input from '$lib/components/ui/input.svelte';
	import Label from '$lib/components/ui/label.svelte';
</script>

<div class="w-full max-w-[420px] space-y-4 rounded-xl border p-4 py-6">
	<div class="text-center">
		<p class="text-xl font-semibold">Sign In into <span class="text-brand">Chattify</span></p>

		<p class="text-sm text-gray-700">Confirm your user to continue using Chattify features.</p>
	</div>

	<form method="POST" class="space-y-4" use:enhance>
		<InputContainer>
			<Label for="email">E-Mail</Label>
			<Input id="email" name="email" type="email" placeholder="example@mail.com" />
		</InputContainer>

		<InputContainer>
			<Label for="password">Password</Label>
			<Input id="password" name="password" type="password" />
		</InputContainer>

		<div>
			<Button type="submit" class="w-full">Sign In</Button>
		</div>
	</form>

	<p class="text-center text-sm text-gray-500">
		Don't have an account? <a href="/register" class="text-brand">Sign Up</a>
	</p>
</div>

// next-client/app/(auth)/login/page.tsx
import { Button } from "@/components/ui/button";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import Link from "next/link";

export default function LoginPage() {
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle>Login</CardTitle>
        <CardDescription>
          Don&apos;t have an account yet?
          <Link href="/register" className="underline text-primary">
            Sign Up
          </Link>
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input id="email" type="email" placeholder="john@example.com" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="password">Password</Label>
          <Input id="password" type="password" />
        </div>
      </CardContent>
      <CardFooter className="flex flex-col space-y-4">
        <Button className="w-full">Sign In</Button>
        <div className="relative w-full">
          <div className="absolute inset-0 flex items-center">
            <span className="w-full border-t" />
          </div>
          <div className="relative flex justify-center text-xs uppercase">
            <span className="bg-white px-2 text-muted-foreground">Or</span>
          </div>
        </div>
        <Button variant="outline" className="w-full" disabled>
          Sign in with Google
        </Button>
      </CardFooter>
    </Card>
  );
}
