// next-client/app/(app)/room/[id]/page.tsx
"use client";

import { RoomBroadcast } from "@/components/room/room-broadcast";
import { RoomLobby } from "@/components/room/room-lobby";
import { useRoomUserStore } from "@/store/room-user-store";
import { RoomUserStatus } from "@/types/room-types";

export default function RoomPage() {
  const status = useRoomUserStore((state) => state.status);

  if (status === RoomUserStatus.Broadcast) {
    return <RoomBroadcast />;
  }

  return <RoomLobby />;
}

// web-client/src/routes/(app)/room/[id]/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import RoomBroadcast from '$lib/components/room-broadcast/room-broadcast.svelte';
	import RoomLobby from '$lib/components/room-lobby/room-lobby.svelte';
	import { wsManager } from '$lib/ws/websocket';
	import { onMount } from 'svelte';
	import { roomStatus } from '../../../../store/room-store';
	import { RoomStatus } from '../../../../types/room-types';
	import RoomChat from '$lib/components/room-chat/room-chat.svelte';

	const { token } = page.data;

	let isLobby = $state(true);
	let status = $state(RoomStatus.Lobby);

	roomStatus.subscribe((state) => (status = state));

	onMount(() => {
		const wsUrl = `ws://localhost:8000/ws?token=${token}`;
		wsManager.connect(wsUrl);

		return () => {
			wsManager.close();
		};
	});
</script>

<div class="flex flex-1">
	{#if status === RoomStatus.Broadcast}
		<RoomBroadcast />
	{:else}
		<RoomLobby />
	{/if}

	<RoomChat containerClassName="flex w-[320px] flex-none flex-col border-l" />
</div>
